<DayActivityIcon>:
    background_normal: ""
    color: [0.5, 0.4, 0.3, 0]
    on_press: root.get_day_info()
    canvas.after:
        Color:
            rgba: [0.2, 0.6, 1, 1]
        Ellipse:
            pos: root.pos
            size: self.width - 2, self.height - 2
<CalendarGrid>:
    GridLayout:
        size: root.width, root.height
        cols: 7
        rows: 7
        padding: 5
        spacing: 2.5
